# What can go wrong if you mix numeric and symbolic computation

Do imports.

In [1]:
import numpy as np
from scipy import linalg
import sympy as sym

## Matrix exponential

### Example 1

An example matrix (numeric).

In [2]:
F = np.array([[1., 2.],
              [3., 4.]])

Taking the matrix exponential (numeric).

In [3]:
linalg.expm(F)

array([[ 51.9689562 ,  74.73656457],
       [112.10484685, 164.07380305]])

Taking the matrix exponential (symbolic).

In [4]:
# Convert from numeric to symbolic matrix
F_sym = sym.Matrix(F)

# Take matrix exponential
sym.exp(F_sym)

Matrix([
[ 51.968956198705, 74.7365645670032],
[112.104846850505,  164.07380304921]])

### Example 2

An example matrix (numeric).

In [5]:
F = np.array([[0.1, 0.2],
              [0.3, 0.4]])

Taking the matrix exponential (numeric).

In [6]:
linalg.expm(F)

array([[1.14209355, 0.26035075],
       [0.39052612, 1.53261967]])

Taking the matrix exponential (symbolic).

In [7]:
# Convert from numeric to symbolic matrix
F_sym = sym.Matrix(F)

# Take matrix exponential
sym.exp(F_sym)

Matrix([
[ 1.14209354891957, 0.260350747540693],
[0.390526121311039,  1.53261967023061]])

### Example 3

An example matrix (numeric).

In [8]:
F = np.array([[0.1, 0.2, 0.3, 0.4],
              [0.5, 0.6, 0.7, 0.8],
              [0.9, 1.0, 1.1, 1.2],
              [1.3, 1.4, 1.5, 1.6]])

Taking the matrix exponential (numeric).

In [9]:
linalg.expm(F)

array([[ 3.28530879,  2.66574821,  3.04618763,  3.42662705],
       [ 5.52144891,  7.2828622 ,  7.0442755 ,  7.80568879],
       [ 8.75758903,  9.89997619, 12.04236336, 12.18475053],
       [11.99372914, 13.51709019, 15.04045123, 17.56381227]])

Taking the matrix exponential (symbolic).

In [10]:
# Convert from numeric to symbolic matrix
F_sym = sym.Matrix(F)

# Take matrix exponential
sym.exp(F_sym)

Matrix([
[3.28530879098647, 2.66574821199239,  3.0461876329983, 3.42662705400421],
[5.52144890799263, 7.28286220299466, 7.04427549799668, 7.80568879299871],
[8.75758902499879, 9.89997619399693, 12.0423633629951, 12.1847505319932],
[11.9937291420049, 13.5170901849992, 15.0404512279934, 17.5638122709877]])

### Example 4

An example matrix (numeric).

In [11]:
F = np.array([[-0.2, 0.0, -0.5, 0.4],
              [-0.8, 0.9, 0.4, 0.8],
              [-0.04, 0.7, -0.81, -0.96],
              [-0.3, -0.3, 0.65, 0.1]])

Taking the matrix exponential (numeric).

In [12]:
linalg.expm(F)

array([[ 0.81992309, -0.24395117, -0.21385137,  0.45999845],
       [-1.35262651,  2.63472916,  0.91384749,  0.79230373],
       [-0.26402259,  0.94208911,  0.47687815, -0.37758242],
       [-0.1657396 , -0.21249307,  0.40086347,  0.71828484]])

Taking the matrix exponential (symbolic).

In [13]:
# Convert from numeric to symbolic matrix
F_sym = sym.Matrix(F)

# Take matrix exponential
sym.exp(F_sym)

KeyboardInterrupt: 

## Differentiation of sines and cosines

Define a symbolic variable.

In [14]:
theta = sym.symbols('theta')

Using `sym.sin`, define a vector-valued function

$$f(\theta) = \begin{bmatrix} \sin(\theta) \end{bmatrix}$$

and compute

$$\dfrac{\partial f}{\partial \theta}.$$

In [15]:
# Define f
f = sym.Matrix([sym.sin(theta)])

# Compute Jacobian
f.jacobian([theta])

Matrix([[cos(theta)]])

Using `np.sin`, define a vector-valued function

$$f(\theta) = \begin{bmatrix} \sin(\theta) \end{bmatrix}$$

and compute

$$\dfrac{\partial f}{\partial \theta}.$$

In [16]:
# Define f
f = sym.Matrix([np.sin(theta)])

# Compute Jacobian
f.jacobian([theta])

TypeError: loop of ufunc does not support argument 0 of type Symbol which has no callable sin method